#!/usr/bin/env node
/**
 * Regenerates src/main/generated-env.ts from `.env` / real environment
 * variables, run right before packaging by scripts/package.mjs.
 *
 * A packaged app has no loose `.env` to read: electron-builder's `files:`
 * allowlist never ships it, and even if it did, main/paths.ts's `APP_ROOT`
 * resolves inside `app.asar` for a packaged build, where a loose file doesn't
 * really live. Baking the values into a compiled module sidesteps both — it
 * ships the normal way, inside `out/**` like every other main-process file.
 *
 * Not wired into the plain `build`/`build:node` scripts on purpose: those run
 * on every dev iteration, and a contributor with real credentials exported in
 * their shell (or a stale .env) should not silently regenerate this file with
 * live values on every `npm start`. Only the packaging path needs it baked in.
 *
 * The real values written here are a package-time artifact, not something
 * that should sit in the tracked working tree afterward — scripts/package.mjs
 * always calls this script again with `--restore` once packaging finishes
 * (success or failure), which writes the blank version back. Run with
 * `--restore` to do that step directly.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const generatedPath = path.join(repoRoot, 'src/main/generated-env.ts');

/** Same minimal parser as main/env.ts's readDotEnv — duplicated so this stays
 * a plain Node script with no ts-node/tsx dependency at package time. */
function readDotEnv(file) {
  const out = {};
  let raw;
  try {
    raw = fs.readFileSync(file, 'utf8');
  } catch {
    return out;
  }
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (trimmed === '' || trimmed.startsWith('#') || !trimmed.includes('=')) continue;
    const eq = trimmed.indexOf('=');
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed
      .slice(eq + 1)
      .trim()
      .replace(/^['"]|['"]$/g, '');
    if (key !== '') out[key] = value;
  }
  return out;
}

function writeGeneratedEnv(apiKey, baseUrl) {
  const banner =
    '/**\n' +
    ' * Build-time defaults for control-plane credentials — GENERATED by\n' +
    ' * scripts/generate-env.mjs immediately before packaging, from `.env` / real\n' +
    ' * environment variables on the machine that ran `npm run package*`.\n' +
    ' *\n' +
    ' * Do not hand-edit real values in here. This committed copy must stay\n' +
    ' * blank — it is what a fresh clone typechecks against and what a package\n' +
    ' * build with no credentials on hand produces. See main/env.ts: a runtime\n' +
    ' * `.env` file or real environment variable still wins over this fallback.\n' +
    ' * scripts/package.mjs restores this file to blank right after packaging,\n' +
    ' * so a real value here is only ever transient on disk, never committed.\n' +
    ' */\n';

  const contents =
    banner +
    'export const BUILT_IN_ENV = {\n' +
    `  apiKey: ${JSON.stringify(apiKey)},\n` +
    `  baseUrl: ${JSON.stringify(baseUrl)},\n` +
    '};\n';

  fs.writeFileSync(generatedPath, contents);
}

if (process.argv.includes('--restore')) {
  writeGeneratedEnv('', '');
  console.log('generate-env: restored src/main/generated-env.ts to blank defaults');
} else {
  const fromFile = readDotEnv(path.join(repoRoot, '.env'));
  const read = (key) => (process.env[key] ?? fromFile[key] ?? '').trim();

  const apiKey = read('RUNANYWHERE_API_KEY');
  const baseUrl = read('RUNANYWHERE_BASE_URL');
  // backendConfig() (src/main/env.ts) only calls itself "production" when
  // BOTH are non-empty. Baking in just one — e.g. a real apiKey with no
  // baseUrl — would ship a live credential inside a build that still
  // self-reports as "development", which is worse than shipping neither:
  // the credential is real, but nothing downstream treats it as such. So
  // partial configuration is not a smaller version of production, it is
  // rejected the same way as no configuration at all.
  const both = apiKey !== '' && baseUrl !== '';

  writeGeneratedEnv(both ? apiKey : '', both ? baseUrl : '');

  if (both) {
    console.log('generate-env: baked in production credentials (apiKey set, baseUrl set)');
  } else if (apiKey || baseUrl) {
    console.log(
      'generate-env: only one of RUNANYWHERE_API_KEY / RUNANYWHERE_BASE_URL is set — ' +
        'writing blank defaults (development). Both are required for a production build.',
    );
  } else {
    console.log('generate-env: no credentials found in .env / environment — blank defaults (development)');
  }
}
