#!/usr/bin/env node
/**
 * Regenerates src/main/generated-env.ts from `.env` / real environment
 * variables, run right before packaging (see the `package*` scripts in
 * package.json).
 *
 * A packaged app has no loose `.env` to read: electron-builder's `files:`
 * allowlist never ships it, and even if it did, main/paths.ts's `APP_ROOT`
 * resolves inside `app.asar` for a packaged build, where a loose file doesn't
 * really live. Baking the values into a compiled module sidesteps both — it
 * ships the normal way, inside `out/**` like every other main-process file.
 *
 * Not wired into the plain `build`/`build:node` scripts on purpose: those run
 * on every dev iteration, and a contributor with real credentials exported in
 * their shell (or a stale .env) should not silently regenerate this file with
 * live values on every `npm start`. Only the packaging path needs it baked in.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

/** Same minimal parser as main/env.ts's readDotEnv — duplicated so this stays
 * a plain Node script with no ts-node/tsx dependency at package time. */
function readDotEnv(file) {
  const out = {};
  let raw;
  try {
    raw = fs.readFileSync(file, 'utf8');
  } catch {
    return out;
  }
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (trimmed === '' || trimmed.startsWith('#') || !trimmed.includes('=')) continue;
    const eq = trimmed.indexOf('=');
    const key = trimmed.slice(0, eq).trim();
    const value = trimmed
      .slice(eq + 1)
      .trim()
      .replace(/^['"]|['"]$/g, '');
    if (key !== '') out[key] = value;
  }
  return out;
}

const fromFile = readDotEnv(path.join(repoRoot, '.env'));
const read = (key) => (process.env[key] ?? fromFile[key] ?? '').trim();

const apiKey = read('RUNANYWHERE_API_KEY');
const baseUrl = read('RUNANYWHERE_BASE_URL');

const banner =
  '/**\n' +
  ' * Build-time defaults for control-plane credentials — GENERATED by\n' +
  ' * scripts/generate-env.mjs immediately before packaging, from `.env` / real\n' +
  ' * environment variables on the machine that ran `npm run package*`.\n' +
  ' *\n' +
  ' * Do not hand-edit real values in here. This committed copy must stay\n' +
  ' * blank — it is what a fresh clone typechecks against and what a package\n' +
  ' * build with no credentials on hand produces. See main/env.ts: a runtime\n' +
  ' * `.env` file or real environment variable still wins over this fallback.\n' +
  ' */\n';

const contents =
  banner +
  'export const BUILT_IN_ENV = {\n' +
  `  apiKey: ${JSON.stringify(apiKey)},\n` +
  `  baseUrl: ${JSON.stringify(baseUrl)},\n` +
  '};\n';

fs.writeFileSync(path.join(repoRoot, 'src/main/generated-env.ts'), contents);

console.log(
  apiKey && baseUrl
    ? 'generate-env: baked in production credentials (apiKey set, baseUrl set)'
    : 'generate-env: no credentials found in .env / environment — blank defaults (development)',
);
